### ISSUE TITLE
Account Page 404

### ISSUE THREAD

**Issue by gilbox** [BitMEX/bitmex-issues#3]
![image](https://cloud.githubusercontent.com/assets/2136203/5747692/9fca3354-9bff-11e4-983d-f275d4a0c879.png)

Clicking the account icon when you're not logged in gives a 404

![image](https://cloud.githubusercontent.com/assets/2136203/5747699/acb98bb4-9bff-11e4-9fb0-bf2ab712e904.png)

**Comment by STRML** [comment]
Thanks. That icon shouldn't show up at all if you're not logged in.

**Comment by STRML** [comment]
This is fixed in all environments - thanks @gilbox!
