### ISSUE TITLE
Bitmex API Performance

### ISSUE THREAD

**Issue by madnight** [BitMEX/bitmex-issues#5]
Hi i think you are already well aware of that issue. The Bitmex API is slow as hell. It is heavily overloaded almost all the time if the volume is a bit higher than usual. You should consider some serious nodejs profiling and performance improving measurements. I think the performance should be at least improved by a factor of x10. I'm not sure where your bottleneck is, but i think this issue can be solved by refactoring and better concurrency handling. The technology choice of kubernetes and nodejs should offer you enough scalability.

**Comment by STRML** [comment]
Our trading engine is not written in nodejs. Node routes orders. We are well aware of the issues and are working to scale the engine while we service load growing 50-70% a month since January 2017.

**Comment by yazeed** [comment]
How is that coming across? API still very slow during peak hours like throughout today's pump.
